@startuml

title __AUTHENTICATION's Class Diagram__\n

  namespace com.gmail.ib.projectCrypt {
    namespace authentication {
      interface AccessControl {
          {static} + ADMIN_ROLE_NAME : String
          {static} + ADMIN_USERNAME : String
          {abstract} + getPrincipalName()
          {abstract} + isUserInRole()
          {abstract} + isUserSignedIn()
          {abstract} + signIn()
          {abstract} + signOut()
      }
    }
  }
  

  namespace com.gmail.ib.projectCrypt {
    namespace authentication {
      class AccessControlFactory {
          {static} - INSTANCE : AccessControlFactory
          + createAccessControl()
          {static} + getInstance()
          - AccessControlFactory()
      }
    }
  }
  

  namespace com.gmail.ib.projectCrypt {
    namespace authentication {
      class BasicAccessControl {
          + getPrincipalName()
          + isUserInRole()
          + isUserSignedIn()
          + signIn()
          + signOut()
      }
    }
  }
  

  namespace com.gmail.ib.projectCrypt {
    namespace authentication {
      class CurrentUser {
          {static} + CURRENT_USER_SESSION_ATTRIBUTE_KEY : String
          {static} + get()
          {static} + set()
          - CurrentUser()
          {static} - getCurrentRequest()
      }
    }
  }
  

  namespace com.gmail.ib.projectCrypt {
    namespace authentication {
      class User {
          - email : String
          - firstName : String
          - lastName : String
          - password : String
          - username : String
          + User()
          + User()
          + getEmail()
          + getFirstName()
          + getLastName()
          + getPassword()
          + getUsername()
          + loadData()
          + setEmail()
          + setFirstName()
          + setLastName()
          + setPassword()
          + setUsername()
      }
    }
  }
  

  AccessControlFactory o-- AccessControl : accessControl
  BasicAccessControl .up.|> AccessControl


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
