@startuml

title __URL's Class Diagram__\n

  namespace com.mysql.cj {
    namespace conf {
      namespace url {
        class com.mysql.cj.conf.url.FailoverConnectionUrl {
            + FailoverConnectionUrl()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace conf {
      namespace url {
        class com.mysql.cj.conf.url.FailoverDnsSrvConnectionUrl {
            {static} - DEFAULT_HOST : String
            {static} - DEFAULT_PORT : int
            + FailoverDnsSrvConnectionUrl()
            + getDefaultHost()
            + getDefaultPort()
            + getHostsList()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace conf {
      namespace url {
        class com.mysql.cj.conf.url.LoadBalanceConnectionUrl {
            + LoadBalanceConnectionUrl()
            + LoadBalanceConnectionUrl()
            + getHostInfoListAsHostPortPairs()
            + getHostInfoListFromHostPortPairs()
            # injectPerTypeProperties()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace conf {
      namespace url {
        class com.mysql.cj.conf.url.LoadBalanceDnsSrvConnectionUrl {
            {static} - DEFAULT_HOST : String
            {static} - DEFAULT_PORT : int
            + LoadBalanceDnsSrvConnectionUrl()
            + getDefaultHost()
            + getDefaultPort()
            + getHostsList()
            # injectPerTypeProperties()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace conf {
      namespace url {
        class com.mysql.cj.conf.url.ReplicationConnectionUrl {
            {static} - TYPE_MASTER : String
            {static} - TYPE_SLAVE : String
            - masterHosts : List<HostInfo>
            - slaveHosts : List<HostInfo>
            + ReplicationConnectionUrl()
            + ReplicationConnectionUrl()
            + getHostsList()
            + getMasterHostOrSpawnIsolated()
            + getMasterHostsListFromHostPortPairs()
            + getMastersListAsHostPortPairs()
            + getSlaveHostOrSpawnIsolated()
            + getSlaveHostsListFromHostPortPairs()
            + getSlavesListAsHostPortPairs()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace conf {
      namespace url {
        class com.mysql.cj.conf.url.ReplicationDnsSrvConnectionUrl {
            {static} - DEFAULT_HOST : String
            {static} - DEFAULT_PORT : int
            {static} - TYPE_MASTER : String
            {static} - TYPE_SLAVE : String
            - masterHosts : List<HostInfo>
            - slaveHosts : List<HostInfo>
            + ReplicationDnsSrvConnectionUrl()
            + getDefaultHost()
            + getDefaultPort()
            + getHostsList()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace conf {
      namespace url {
        class com.mysql.cj.conf.url.SingleConnectionUrl {
            + SingleConnectionUrl()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace conf {
      namespace url {
        class com.mysql.cj.conf.url.XDevApiConnectionUrl {
            {static} - DEFAULT_PORT : int
            - hasDuplicatedPriorities : boolean
            - prioritySorted : boolean
            + XDevApiConnectionUrl()
            + getDefaultPort()
            + getHostsList()
            # fixProtocolDependencies()
            # preprocessPerTypeHostProperties()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace conf {
      namespace url {
        class com.mysql.cj.conf.url.XDevApiDnsSrvConnectionUrl {
            {static} - DEFAULT_HOST : String
            {static} - DEFAULT_PORT : int
            + XDevApiDnsSrvConnectionUrl()
            + getDefaultHost()
            + getDefaultPort()
            + getHostsList()
            # fixProtocolDependencies()
            # preprocessPerTypeHostProperties()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
